# Use root/example as user/password credentials
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: lotto
    volumes:
      - ../volumes/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - lottery-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
    - mongo
    networks:
    - lottery-net

  discovery-server:
    build: discovery-server-service
    image: julekkl/lottery/discovery-server:latest
    container_name: discovery-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - lottery-net

  gateway-service:
    build: gateway-service
    image: julekkl/lottery/gateway-service:latest
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    networks:
      - lottery-net
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/

  numbers-generator:
    build: numbers-generator
    image: julekkl/lottery/numbers-generator
    container_name: numbers-generator
    restart: always
    depends_on:
      - mongo
      - discovery-server
      - gateway-service
    networks:
      - lottery-net
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
      spring.data.mongodb.host: mongo

  lotto-engine:
    build: lotto-engine
    image: julekkl/lottery/lotto-engine
    container_name: lotto-engine
    restart: always
    depends_on:
      - mongo
      - discovery-server
      - gateway-service
    networks:
      - lottery-net
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-server:8761/eureka/
      spring.data.mongodb.host: mongo

networks:
  lottery-net:
    driver: bridge