spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lotto
      username: admin
      password: admin

lotto:
  result-announcer:
    win-message-received: "Congratulations you have won!"
    win-message-not-received: "Congratulations you have won, but already received reward."
    lose-message: "Unfortunately you didn't won."