spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lotto
      username: admin
      password: admin
#      uri: mongodb://admin:admin@localhost:27017/lotto
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace