spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lotto
      username: admin
      password: admin

lotto:
  result-announcer:
    win-message: "Congratulations you have won!"
    lose-message: "Unfortunately you didn't won."