server:
  port: 8070

spring:
  application:
    name: mail-service
  config:
    import: optional:file:.env[.properties]
  cloud:
    config:
      enabled: false

queues:
  names:
    account-created-event: email.service

email:
  sender:
    enabled: false
    address: ${EMAIL_HOST_ADDRESS}

logging:
  level:
    pl:
      lotto: debug
    root: info