version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:23.0.1
        user: root

jobs:

  lint:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run Checkstyle Linting
          command: |
            for service in authentication-service; do
              echo "Running linting checks for $service"
              cd $service
              mvn checkstyle:check
              cd -
            done

  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: default
          docker_layer_caching: true
      - run:
          name: Build Docker Images and Compile Code
          command: |
            for service in authentication-service; do
              echo "Building Docker image for $service"
              docker build -t $service ./$service
            done
      - run:
          name: Save Docker image as tar
          command: |
            docker save authentication-service --output /home/circleci/project/authentication-service.tar
      - run:
          name: Run Unit Tests
          command: |
            for service in authentication-service; do
              echo "Running unit test for image $service"
              docker build -t $service-test --progress=plain --no-cache --target=test ./$service
              echo "Removing test image for $service" docker rmi $service-test
              docker rmi $service-test
            done
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .

  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Load Docker Image
          command: |
            docker load --input /home/circleci/project/authentication-service.tar
      - run:
          name: Run Integration Tests
          command: |
            for service in authentication-service; do
              echo "TODO Implement integration test runner. Running integration tests for $service"
              docker run --entrypoint "" -v /var/run/docker.sock:/var/run/docker.sock authentication-service mvn verify -Dskip.ut=true
            done
#                                        TO DZIAŁA LOKALNIE \/
#  docker run --entrypoint "" -v /var/run/docker.sock.raw:/var/run/docker.sock julekkl/lottery/authentication-service:latest mvn verify -Dskip.ut=true

#              docker run -it --rm --entrypoint "" -v $PWD:$PWD -w $PWD -v /var/run/docker.sock:/var/run/docker.sock $service-test ./mvnw verify -Dskip.ut=true
#  docker run --entrypoint "" -v /var/run/docker.sock:/var/run/docker.sock julekkl/lottery/authentication-service:latest mvn verify -Dskip.ut=true
#  docker run -it --rm --entrypoint "" -v $PWD:$PWD -w $PWD -v /var/run/docker.sock:/var/run/docker.sock julekkl/lottery/authentication-service ./mvnw verify -Dskip.ut=true
                     #            mvn clean verify -Dskip.ut=true
#            docker run --rm --entrypoint "" -v /var/run/docker.sock:/var/run/docker.sock -e TESTCONTAINERS_RYUK_DISABLED=true julekkl/lottery/authentication-service:latest mvn verify
#            RUN apk add --no-cache maven
#                     docker run -it --rm --entrypoint "" -v $PWD:$PWD -w $PWD -v /var/run/docker.sock:/var/run/docker.sock julekkl/lottery/authentication-service ./mvnw test
  #              docker run $service mvn verify
#            aws ecr get-login-password --region your-region | docker login --username AWS --password-stdin your-ecr-repository-url
#              docker tag $service:latest your-ecr-repository-url/$service:latest
#              docker push your-ecr-repository-url/$service:latest
#  for service in gateway-service config-server authentication-service discovery-server-service lotto-engine numbers-generator mail-service; do
  #            docker build -f ../authentication-service/Dockerfile  -t app --progress=plain --no-cache --target=test ../
  release:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Push Docker Images to ECR
          command: |
            for service in authentication-service; do
              echo "TODO Pushing $service to ECR"
            done

workflows:
  version: 2
  build-test-deploy:
    jobs:
#      - lint
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test

#      - hold:
#          type: approval
#          requires:
#            - build
#      - deploy:
#          requires:
#            - hold
#  test:
#    docker:
#      - image: cimg/openjdk:21.0.2
#    steps:
#      - checkout
#      - run:
#          name: Print Java version
#          command: |
#            java --version
#      - run:
#          name: Install dependencies
#          command: mvn clean install -DskipTests
#      - run:
#          name: Run tests
#          command: mvn test