version: 2.1

workflows:
  run_tests:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run: java --version
      - run: mvn clean install
      - run: mvn test
