version: 2.1

workflows:
  run_tests:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
            name: Print Java version
            command: |
              java --version
      - run: 
            name: Install dependencies
            command: mvn clean install
      - run: 
            name: Run tests
            command: mvn test
