server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: TRACE

jwt:
  secret: 164d16c51adcac4b0a8772cfac8215f7d1f7fbf0d88904aa66d2f68ca5a32160847495424817fb4751e5b9e3815dbd56ddc819a4ea73fb3e9fe0283633a2bdd17cacf6dbafe86398846487fb70d5101855bc9ba1f37c32b97eeafa573095111c64c5997ecb9f6675e5998dc6d32a6af606ca06f3c73b9b3a7a981b79d15b91835f6b716a73bad52fb011e339a592aaa76408325d94a1a818a7612dcc1ed028577c350f98752befa38308fdd6e8d1af740c4628594320c1fa141e4d19f54ce716f1b2a220b3bbe2841d8b13e044b49cc56dcab89d69d95ca2dc99075e11be3e06bc0e55c6159ff5177e18d7feb08453ae0f3843d355c0942a647ce278e61d37ca
  expiration:
    minutes: 5
    seconds: 60
    millis: 1000
    access: '#{${jwt.expiration.minutes}*${jwt.expiration.seconds}*${jwt.expiration.millis}}'
    refresh: '#{${jwt.expiration.minutes}*${jwt.expiration.seconds}*${jwt.expiration.millis}*10}'

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: LOTTO-ENGINE
          uri: lb://lotto-engine
          predicates:
            - Path=/lottery/**,/result/**
          filters:
            - AuthenticationFilter
        - id: LOTTO-ENGINE-swagger
          uri: lb://lotto-engine
          predicates:
            - Path=/lotto-engine/v3/api-docs
            - Method=GET
        - id: NUMBERS-GENERATOR-swagger
          uri: lb://numbers-generator
          predicates:
            - Path=/numbers-generator/v3/api-docs
            - Method=GET
        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: AUTH-SERVICE-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/v3/api-docs
            - Method=GET

#http://localhost:8080/swagger-ui.html
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
      - url: /lotto-engine/v3/api-docs
        name: Lotto Engine
      - url: /numbers-generator/v3/api-docs
        name: Numbers Generator
      - url: /auth-service/v3/api-docs
        name: Authentication Service
    disable-swagger-default-url: true
    path: /swagger