server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: TRACE


spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: LOTTO-ENGINE
          uri: lb://lotto-engine
          predicates:
            - Path=/lottery/**,/result/**
          filters:
            - StripPrefix=1
        - id: LOTTO-ENGINE-swagger
          uri: lb://lotto-engine
          predicates:
            - Path=/lotto-engine/v3/api-docs
            - Method=GET
        - id: NUMBERS-GENERATOR-swagger
          uri: lb://numbers-generator
          predicates:
            - Path=/numbers-generator/v3/api-docs
            - Method=GET

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
#      - url: /v3/api-docs
#        name: API Gateway Service
      - url: /lotto-engine/v3/api-docs
        name: Lotto Engine
      - url: /numbers-generator/v3/api-docs
        name: Numbers Generator