lotto:
  number-generator:
    service:
      url: "http://localhost"
  result-checker:
    scheduler-cron: "*/4 * * * * *"

eureka:
  client:
    enabled: false

spring:
  cloud:
    loadbalancer:
      enabled: false

