spring:
  application:
    name: lotto-engine
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lotto
      username: admin
      password: admin
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

lotto:
  time:
    drawDayOfWeek: 5
    drawHour: 20
    drawMinute: 0
    resultsMinute: 1
    drawSecond: 0
    drawTime: "${lotto.time.drawHour}:${lotto.time.drawMinute}:${lotto.time.drawSecond}}"
  result-announcer:
    win-message-received: "Congratulations you have won, but already received reward."
    win-message-not-received: "Congratulations you have won, you can receive reward."
    lose-message: "Unfortunately you didn't won."
  number-generator:
    scheduler-cron: "${lotto.time.drawSecond} ${lotto.time.drawMinute} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"
  result-checker:
    scheduler-cron: "${lotto.time.drawSecond} ${lotto.time.resultsMinute} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"
